name: Esegui Master Engine

on:
  workflow_dispatch: # Ti permette di lanciare il bot manualmente con il tasto Play
  push:
    paths:
      - 'Lista-FantaAsta-Fantacalcio.csv' # Si avvia da solo se aggiorni questo file
      - 'Quotazioni_Fantacalcio_Stagione_2025_26.xlsx'

jobs:
  aggiorna_database:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Dà al bot il permesso di salvare file nella tua repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa Librerie
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui Motore e Scout
        run: python build_master.py
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }} # <-- La chiave della cassaforte!

      - name: Salva il nuovo File Master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "FantaBot GitHub Action"
          git add Lista_Finale_Master.csv
          git commit -m "Aggiornamento: Nuovo Master CSV generato con dati Scout" || echo "Nessun nuovo dato da salvare"
          git push
